# This is a sample hosts configuration file for deployer.
# When you use vagrant for development, this hosts file can be used to test
# the deployment. For production, copy this file, and update the following
# configuration (don't put the new file under source control).
vagrant:
  stage: development
  user: vagrant
  deploy_path: ~/{{application}}
  public_path: /var/www/kwai_dev_api
